package main

/*
	Discord holds information about a discord server, the channel messages are posted to
	The apiKey can be generated by the master of the server to do api requests with
*/
type Discord struct {
	ServerID  string `json:"serverid" bson:"serverid"`
	ChannelID string `json:"channelid" bson:"channelid"`
	APIKey    string `json:"apikey" bson:"apikey"`
}
